name: mater-iron
channels:
- defaults
- conda-forge
- matsci
dependencies:
- anaconda=4.4.0=np112py36_0
- ase=3.15.0=py36_1
- autopep8=1.3.3=py_0
- blinker=1.4=py36_0
- brewer2mpl=1.4.1=py36_2
- certifi=2017.7.27.1=py36_0
- flake8=3.3.0=py36_0
- flask-paginate=0.4.5=py36h53e8154_0
- future=0.16.0=py36_1
- gunicorn=19.1.0=py36_0
- ipython=5.3.0=py36_0
- json-rpc=1.10.3=py36_0
- jupyter_contrib_nbextensions=0.3.1=py36_0
- jupyter_kernel_gateway=2.0.2=py_0
- lesscpy=0.12.0=py36_0
- lockfile=0.12.2=py36_0
- markdown=2.6.9=py36_0
- monty=1.0.0=py36_2
- palettable=3.1.0=py_0
- pandoc-attributes=0.1.7=py36_0
- pandoc=1.15.0.6=0
- pluggy=0.6.0=py_0
- pweave=0.30.1=py36_0
- pydispatcher=2.0.5=py36_0
- pydocstyle=2.0.0=py36_0
- pylama=7.4.3=py_0
- pymongo=3.4.0=py36_0
- python-daemon=2.1.2=py36_0
- python-language-server=0.8.0=py36_0
- ruamel.yaml=0.15.34=py36_0
- spglib=1.10.1.4=py36_0
- tabulate=0.8.1=py_0
- tikzmagic=0.1.0=py36_0
- tqdm=4.15.0=py36_0
- yapf=0.18.0=py_0
